language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
notifications:
  webhooks:
    urls:
      - https://aws02-g23-uds01.dev.glip.net:22815/webhook/4062e0c5-055a-4f0d-b4d8-49ee99bb152f
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
