language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
notifications:
  webhooks:
    urls:
      - https://hooks-aws11g07uds05.dev.glip.net/webhook/3f585072-92db-4e09-bc22-e0edde3a9410
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never

